// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateEventEventsCreatePostData, CreateEventEventsCreatePostErrors, CreateEventEventsCreatePostResponses, GetEventDetailsEventsEventIdGetData, GetEventDetailsEventsEventIdGetErrors, GetEventDetailsEventsEventIdGetResponses, GetEventsEventsGetData, GetEventsEventsGetResponses, GetUserSharesUsersUserIdSharesGetData, GetUserSharesUsersUserIdSharesGetErrors, GetUserSharesUsersUserIdSharesGetResponses, GetUsersUsersGetData, GetUsersUsersGetResponses, GetUserUsersCurrentGetData, GetUserUsersCurrentGetResponses, LoginAuthLoginPostData, LoginAuthLoginPostErrors, LoginAuthLoginPostResponses, PlaceBetEventsBetPostData, PlaceBetEventsBetPostErrors, PlaceBetEventsBetPostResponses, RegisterUserAuthRegisterPostData, RegisterUserAuthRegisterPostErrors, RegisterUserAuthRegisterPostResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register User
 */
export const registerUserAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterUserAuthRegisterPostData, ThrowOnError>) => (options.client ?? client).post<RegisterUserAuthRegisterPostResponses, RegisterUserAuthRegisterPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginAuthLoginPostResponses, LoginAuthLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Get Users
 */
export const getUsersUsersGet = <ThrowOnError extends boolean = false>(options?: Options<GetUsersUsersGetData, ThrowOnError>) => (options?.client ?? client).get<GetUsersUsersGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/',
    ...options
});

/**
 * Get User Shares
 */
export const getUserSharesUsersUserIdSharesGet = <ThrowOnError extends boolean = false>(options: Options<GetUserSharesUsersUserIdSharesGetData, ThrowOnError>) => (options.client ?? client).get<GetUserSharesUsersUserIdSharesGetResponses, GetUserSharesUsersUserIdSharesGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}/shares',
    ...options
});

/**
 * Get User
 */
export const getUserUsersCurrentGet = <ThrowOnError extends boolean = false>(options?: Options<GetUserUsersCurrentGetData, ThrowOnError>) => (options?.client ?? client).get<GetUserUsersCurrentGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/current',
    ...options
});

/**
 * Get Events
 */
export const getEventsEventsGet = <ThrowOnError extends boolean = false>(options?: Options<GetEventsEventsGetData, ThrowOnError>) => (options?.client ?? client).get<GetEventsEventsGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/',
    ...options
});

/**
 * Get Event Details
 */
export const getEventDetailsEventsEventIdGet = <ThrowOnError extends boolean = false>(options: Options<GetEventDetailsEventsEventIdGetData, ThrowOnError>) => (options.client ?? client).get<GetEventDetailsEventsEventIdGetResponses, GetEventDetailsEventsEventIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{event_id}',
    ...options
});

/**
 * Create Event
 */
export const createEventEventsCreatePost = <ThrowOnError extends boolean = false>(options: Options<CreateEventEventsCreatePostData, ThrowOnError>) => (options.client ?? client).post<CreateEventEventsCreatePostResponses, CreateEventEventsCreatePostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Place Bet
 */
export const placeBetEventsBetPost = <ThrowOnError extends boolean = false>(options: Options<PlaceBetEventsBetPostData, ThrowOnError>) => (options.client ?? client).post<PlaceBetEventsBetPostResponses, PlaceBetEventsBetPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/bet',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
