// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://10.0.0.165:8051' | (string & {});
};

/**
 * Body_login_auth_login_post
 */
export type BodyLoginAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_place_bet_events_bet_post
 */
export type BodyPlaceBetEventsBetPost = {
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Price Per Share
     */
    price_per_share: number;
};

/**
 * Event
 */
export type Event = {
    /**
     * Title
     */
    title: string;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    type: EventType;
    /**
     * Value
     */
    value: number;
    /**
     * First Share Bonus
     */
    first_share_bonus?: number;
    /**
     * Finalized
     */
    finalized?: boolean;
    /**
     * Id
     */
    id?: string;
};

/**
 * EventCreate
 */
export type EventCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    type: EventType;
    /**
     * Value
     */
    value: number;
    /**
     * First Share Bonus
     */
    first_share_bonus?: number;
    /**
     * Finalized
     */
    finalized?: boolean;
    /**
     * Outcomes
     */
    outcomes: Array<OutcomeBase>;
};

/**
 * EventReadWithShares
 */
export type EventReadWithShares = {
    /**
     * Title
     */
    title: string;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    type: EventType;
    /**
     * Value
     */
    value: number;
    /**
     * First Share Bonus
     */
    first_share_bonus?: number;
    /**
     * Finalized
     */
    finalized?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Outcomes
     */
    outcomes?: Array<OutcomeRead>;
    /**
     * Shares
     */
    shares?: Array<ShareRead>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IconCreate
 */
export type IconCreate = {
    /**
     * Icon Url
     */
    icon_url: string;
    /**
     * Random
     */
    random: boolean;
};

/**
 * OutcomeBase
 */
export type OutcomeBase = {
    /**
     * Description
     */
    description: string;
    /**
     * Value
     */
    value: number;
    /**
     * Cost
     */
    cost?: number;
    /**
     * Event Id
     */
    event_id?: string | null;
};

/**
 * OutcomeRead
 */
export type OutcomeRead = {
    /**
     * Description
     */
    description: string;
    /**
     * Value
     */
    value: number;
    /**
     * Cost
     */
    cost?: number;
    /**
     * Event Id
     */
    event_id?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * ShareRead
 */
export type ShareRead = {
    /**
     * Id
     */
    id?: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Value
     */
    value: number;
    /**
     * Wager
     */
    wager: number;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * TokenBase
 */
export type TokenBase = {
    /**
     * Token
     */
    token: string;
    /**
     * Used
     */
    used?: boolean;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Balance
     */
    balance?: number;
    /**
     * Icon Url
     */
    icon_url?: string;
    /**
     * Password
     */
    password: string;
    /**
     * Token
     */
    token: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Username
     */
    username: string;
    /**
     * Balance
     */
    balance?: number;
    /**
     * Icon Url
     */
    icon_url?: string;
    /**
     * Id
     */
    id: string;
};

/**
 * UserReadWithShares
 */
export type UserReadWithShares = {
    /**
     * Username
     */
    username: string;
    /**
     * Balance
     */
    balance?: number;
    /**
     * Icon Url
     */
    icon_url?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Shares
     */
    shares?: Array<ShareRead>;
    /**
     * Admin
     */
    admin?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * eventType
 */
export type EventType = 'over/under' | 'singleton' | 'multiple-choice';

export type RegisterUserAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterUserAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserAuthRegisterPostError = RegisterUserAuthRegisterPostErrors[keyof RegisterUserAuthRegisterPostErrors];

export type RegisterUserAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterUserAuthRegisterPostResponse = RegisterUserAuthRegisterPostResponses[keyof RegisterUserAuthRegisterPostResponses];

export type RegisterNewTokenAuthRegisterTokenGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/register/token';
};

export type RegisterNewTokenAuthRegisterTokenGetResponses = {
    /**
     * Successful Response
     */
    200: TokenBase;
};

export type RegisterNewTokenAuthRegisterTokenGetResponse = RegisterNewTokenAuthRegisterTokenGetResponses[keyof RegisterNewTokenAuthRegisterTokenGetResponses];

export type LoginAuthLoginPostData = {
    body: BodyLoginAuthLoginPost;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetUsersUsersGetResponses = {
    /**
     * Response Get Users Users  Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersUsersGetResponse = GetUsersUsersGetResponses[keyof GetUsersUsersGetResponses];

export type GetUserSharesUsersUserIdSharesGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/shares';
};

export type GetUserSharesUsersUserIdSharesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserSharesUsersUserIdSharesGetError = GetUserSharesUsersUserIdSharesGetErrors[keyof GetUserSharesUsersUserIdSharesGetErrors];

export type GetUserSharesUsersUserIdSharesGetResponses = {
    /**
     * Successful Response
     */
    200: UserReadWithShares;
};

export type GetUserSharesUsersUserIdSharesGetResponse = GetUserSharesUsersUserIdSharesGetResponses[keyof GetUserSharesUsersUserIdSharesGetResponses];

export type GetUserUsersCurrentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/current';
};

export type GetUserUsersCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: UserReadWithShares;
};

export type GetUserUsersCurrentGetResponse = GetUserUsersCurrentGetResponses[keyof GetUserUsersCurrentGetResponses];

export type PostIconUsersIconPostData = {
    body: IconCreate;
    path?: never;
    query?: never;
    url: '/users/icon';
};

export type PostIconUsersIconPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostIconUsersIconPostError = PostIconUsersIconPostErrors[keyof PostIconUsersIconPostErrors];

export type PostIconUsersIconPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type PostIconUsersIconPostResponse = PostIconUsersIconPostResponses[keyof PostIconUsersIconPostResponses];

export type GetEventsEventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/';
};

export type GetEventsEventsGetResponses = {
    /**
     * Response Get Events Events  Get
     *
     * Successful Response
     */
    200: Array<Event>;
};

export type GetEventsEventsGetResponse = GetEventsEventsGetResponses[keyof GetEventsEventsGetResponses];

export type GetEventDetailsEventsEventIdGetData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/events/{event_id}';
};

export type GetEventDetailsEventsEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventDetailsEventsEventIdGetError = GetEventDetailsEventsEventIdGetErrors[keyof GetEventDetailsEventsEventIdGetErrors];

export type GetEventDetailsEventsEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventReadWithShares;
};

export type GetEventDetailsEventsEventIdGetResponse = GetEventDetailsEventsEventIdGetResponses[keyof GetEventDetailsEventsEventIdGetResponses];

export type CreateEventEventsCreatePostData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/events/create';
};

export type CreateEventEventsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEventEventsCreatePostError = CreateEventEventsCreatePostErrors[keyof CreateEventEventsCreatePostErrors];

export type CreateEventEventsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type CreateEventEventsCreatePostResponse = CreateEventEventsCreatePostResponses[keyof CreateEventEventsCreatePostResponses];

export type PlaceBetEventsBetPostData = {
    body: BodyPlaceBetEventsBetPost;
    path?: never;
    query: {
        /**
         * Event Id
         */
        event_id: number;
    };
    url: '/events/bet';
};

export type PlaceBetEventsBetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlaceBetEventsBetPostError = PlaceBetEventsBetPostErrors[keyof PlaceBetEventsBetPostErrors];

export type PlaceBetEventsBetPostResponses = {
    /**
     * Response Place Bet Events Bet Post
     *
     * Successful Response
     */
    200: Array<ShareRead>;
};

export type PlaceBetEventsBetPostResponse = PlaceBetEventsBetPostResponses[keyof PlaceBetEventsBetPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
